---
- hosts: ec2machines
  connection: ssh
  gather_facts: yes

  tasks:
    - name: Update packages
      apt: name= '*' state=latest
	  
#   - name: install required packages using the apt module
#     apt: package={{ item }}  update_cache=yes
#     with_items:
#      - curl
#      - wget
	   
    - name: Put a config file in place
      template: src=awslogs.conf.j2 dest=/tmp/awslogs.conf group=root mode=0600 owner=root 	   
       
    - name: Download the installer
      get_url: url=https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py dest=/tmp/awslogs-agent-setup.py group=root owner=root mode=0600
      
    - name: Install the CloudWatch Logs agent
      shell: python /tmp/awslogs-agent-setup.py -n -r us-east-1 -c /tmp/awslogs.conf
		 
    - name: Copy systemd unit file
      copy: src=awslogs.service dest=/lib/systemd/system/awslogs.service owner=root group=root mode=644 backup=yes
	 
    - name: Enable the service
      shell: "systemctl enable awslogs.service"
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'
    
    - name: Enable the service
      service: name=awslogs enabled=yes
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

    - name: Start the service
      service: name=awslogs state=started


  handlers:
   - name: Remove /tmp/awslogs.conf
     file: path=/tmp/awslogs.conf state=absent

   - name: Remove /tmp/awslogs-agent-setup.py
     file: path=/tmp/awslogs-agent-setup.py state=absent

